[build.environment]
  PYTHON_VERSION = "3.9"

[build]
  command = """
    wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.537/quarto-1.4.537-linux-amd64.tar.gz && \
    tar -xvf quarto-1.4.537-linux-amd64.tar.gz && \
    export PATH="$PATH:$(pwd)/quarto-1.4.537/bin" && \
    python -m pip install --upgrade pip && \
    python -m pip install jupyter && \
    quarto install extension quarto-ext/listing -y && \
    quarto install extension jmgirard/embedpdf -y && \
    quarto install extension quarto/title-block -y && \
    quarto render
  """
  publish = "_site"
