[build.environment]
  PYTHON_VERSION = "3.9"

[build]
  command = """
    wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.537/quarto-1.4.537-linux-amd64.tar.gz && \
    tar -xvf quarto-1.4.537-linux-amd64.tar.gz && \
    export PATH="$PATH:$(pwd)/quarto-1.4.537/bin" && \
    python -m pip install --upgrade pip && \
    python -m pip install jupyter && \
    mkdir -p ~/.local/share/quarto/extensions/jmgirard/embedpdf && \
    cp -r _extensions/jmgirard/embedpdf/* ~/.local/share/quarto/extensions/jmgirard/embedpdf/ && \
    quarto render index.qmd about.qmd cv.qmd research.qmd resources.qmd ws.qmd --output-dir _site
  """
  publish = "_site"
