[build.environment]
  PYTHON_VERSION = "3.9"

[build]
  command = """
    wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.537/quarto-1.4.537-linux-amd64.deb && \
    sudo dpkg -i quarto-1.4.537-linux-amd64.deb && \
    python -m pip install --upgrade pip && \
    python -m pip install jupyter && \
    quarto render
  """
  publish = "_site"
